django/mycontacts/contacts/mobile/urls.py
from django.urls import path

from .views import index

app_name = "mobile"
urlpatterns = [path("", index, name="index")]

django/mycontacts/contacts/urls.py
from django.urls import path, include

from .views import (
    index,
    archive,
    archive_content,
    reset_archive,
    contacts_count,
    new_contact,
    details,
    edit,
    validate_email,
    delete,
    delete_all,
)

app_name = "contacts"

urlpatterns = [
    path("", index, name="index"),
    path("archive/", archive, name="archive"),
    path("new/", new_contact, name="new"),
    path("archive/content/", archive_content, name="archive_content"),
    path("archive/reset/", reset_archive, name="reset_archive"),
    path("count/", contacts_count, name="count"),
    path("delete-all/", delete_all, name="delete_all"),
    path("mobile/", include("contacts.mobile.urls", namespace="mobile")),
    path("<int:pk>/", details, name="details"),
    path("<int:pk>/edit/", edit, name="edit"),
    path("<int:pk>/delete/", delete, name="delete"),
    path("<int:pk>/validate_email/", validate_email, name="validate_email"),
]

django/mycontacts/mycontacts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("contacts.urls", namespace="contacts")),
]

django/mycontacts/contacts/models.py
from functools import partial

import requests
from django.db import models

NullBlankCharField = partial(models.CharField, blank=True, null=True, max_length=255)


class Contact(models.Model):
    first_name = NullBlankCharField()
    last_name = NullBlankCharField()
    phone = NullBlankCharField()
    email = models.EmailField(unique=True)

    @classmethod
    def populate_db(cls):
        url = "https://raw.githubusercontent.com/bigskysoftware/contact-app/master/contacts.json"
        r = requests.get(url)
        for c in r.json():
            cls.objects.get_or_create(
                first_name=c["first"],
                last_name=c["last"],
                phone=c["phone"],
                email=c["email"],
            )

    @classmethod
    def search(cls, text):
        return cls.objects.filter(
            models.Q(first_name__icontains=text)
            | models.Q(last_name__icontains=text)
            | models.Q(phone__icontains=text)
            | models.Q(email__icontains=text)
        ).order_by("email")

django/mycontacts/contacts/forms.py
from django import forms

from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["first_name", "last_name", "phone", "email"]

django/mycontacts/contacts/mobile/views.py
from functools import partial

from django.core.paginator import Paginator
from django.http import HttpResponse
from django.template.response import TemplateResponse
from render_block import render_block_to_string

from ..models import Contact

HXMLResponse = partial(TemplateResponse, content_type="application/vnd.hyperview+xml")


def index(request):
    search = request.GET.get("q")
    page_number = int(request.GET.get("page", 1))
    rows_only = request.GET.get("rows_only") == "true"
    if search:
        contacts = Contact.search(search)
    else:
        contacts = Contact.objects.order_by("email")

    paginator = Paginator(contacts, 15)
    page = paginator.get_page(page_number)

    template_name = "mobile/rows.xml" if rows_only else "mobile/index.xml"
    # return HXMLResponse(request, template_name, {"page": page})
    template_name = "mobile/index.xml"
    if rows_only:
        data = render_block_to_string(template_name, "rows", {"page": page})
        print(data)
        return HttpResponse(data, content_type="application/vnd.hyperview+xml")
    return HXMLResponse(request, template_name, {"page": page})

django/mycontacts/contacts/views.py
from django.contrib import messages
from django.http import FileResponse
from django.http import QueryDict
from django.shortcuts import redirect, get_object_or_404
from django.template.response import TemplateResponse, HttpResponse
from django.views.decorators.http import require_http_methods

from .forms import ContactForm
from .models import Contact
from .utils import Archiver


def index(request):
    # Contact.populate_db()
    search = request.GET.get("q")
    if search is not None and request.headers.get("HX-Trigger") == "search":
        return TemplateResponse(
            request, "rows.html", {"contacts": Contact.search(search)}
        )
    return TemplateResponse(
        request,
        "index.html",
        {"contacts": Contact.objects.all(), "archiver": Archiver.get()},
    )


def archive(request):
    archiver = Archiver.get()
    if request.method == "POST":
        archiver.run()
    return TemplateResponse(request, "archive_ui.html", {"archiver": archiver})


def archive_content(request):
    archiver = Archiver.get()

    response = FileResponse(archiver.archive_content(), content_type="application/json")
    response["Content-Disposition"] = 'attachment; filename="archive.json"'
    return response


@require_http_methods(["DELETE"])
def reset_archive(request):
    archiver = Archiver.get()
    archiver.reset()
    return TemplateResponse(request, "archive_ui.html", {"archiver": archiver})


def contacts_count(request):
    count = Contact.objects.count()
    return HttpResponse(f"({str(count)} total Contacts)")


def new_contact(request):
    form = ContactForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        messages.success(request, "Created New Contact!")
        form.save()
        return redirect("contacts:index")
    return TemplateResponse(request, "new.html", {"form": form})


def details(request, pk):
    contact = Contact.objects.get(pk=pk)
    return TemplateResponse(request, "details.html", {"contact": contact})


def edit(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    form = ContactForm(request.POST or None, instance=contact)
    if request.method == "POST" and form.is_valid():
        messages.success(request, "Updated Contact!")
        form.save()
        return redirect("contacts:details", pk=pk)
    return TemplateResponse(request, "edit.html", {"form": form, "contact": contact})


def validate_email(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    form = ContactForm(request.GET or None, instance=contact)
    if form.is_valid():
        return HttpResponse("")
    return HttpResponse(form.errors["email"][0])


@require_http_methods(["DELETE"])
def delete(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    contact.delete()
    if request.headers.get("HX-Trigger") == "delete-btn":
        messages.info(request, "Deleted Contact!")
        return redirect("contacts:index")
    return HttpResponse("")


@require_http_methods(["DELETE"])
def delete_all(request):
    params = QueryDict(request.body)
    contact_ids = list(map(int, params.getlist("selected_contact_ids")))
    Contact.objects.filter(pk__in=contact_ids).delete()
    messages.info(request, "Deleted Contacts!")
    return redirect("contacts:index")

django/mycontacts/templates/archive_ui.html
<div id="archive-ui" hx-target="this" hx-swap="outerHTML">
    {% if archiver.status == "Waiting" %}
        <button hx-post="{% url 'contacts:archive' %}">
            Download Contact Archive
        </button>
    {% elif archiver.status == "Running" %}
        <div hx-get="{% url 'contacts:archive' %}" hx-trigger="load delay:500ms">
            Creating Archive...
            <div class="progress">
                <div id="archive-progress" class="progress-bar"
                     style="width:{% widthratio archiver.progress 1 100 %}%"></div>
            </div>
        </div>
    {% elif archiver.status == "Complete" %}
        <a hx-boost="false" href="{% url 'contacts:archive_content' %}" _="on load click() me">Archive Downloading!
            Click here if the
            download does not start.</a>
        <button hx-delete="{% url 'contacts:reset_archive' %}">Clear Download</button>
    {% endif %}
</div>

django/mycontacts/templates/details.html
{% extends 'layout.html' %}

{% block content %}

    <h1>{{ contact.first_name }} {{ contact.last_name }}</h1>

    <div>
        <div>Phone: {{ contact.phone }}</div>
        <div>Email: {{ contact.email }}</div>
    </div>

    <p>
        <a href="{% url 'contacts:edit' contact.id %}">Edit</a>
        <a href="{% url 'contacts:index' %}">Back</a>
    </p>


{% endblock %}

django/mycontacts/templates/edit.html
{% extends 'layout.html' %}

{% block content %}

    <form action="{% url 'contacts:edit' contact.pk %}" method="post">
        <fieldset>
            <legend>Contact Values</legend>
            <div class="table rows">
                <p>
                    <label for="email">Email</label>
                    <input name="email" id="email" type="email"
                           hx-get="{% url 'contacts:validate_email' contact.pk %}"
                           hx-target="next .error"
                           hx-trigger="change, keyup delay:200ms"
                           placeholder="Email" value="{{ contact.email }}">
                    <span class="error">{{ form.errors.email }}</span>
                </p>
                <p>
                    <label for="first_name">First Name</label>
                    <input name="first_name" id="first_name" type="text" placeholder="First Name"
                           value="{{ contact.first_name }}">
                    <span class="error">{{ form.errors.first_name }}</span>
                </p>
                <p>
                    <label for="last_name">Last Name</label>
                    <input name="last_name" id="last_name" type="text" placeholder="Last Name"
                           value="{{ contact.last_name }}">
                    <span class="error">{{ form.errors.last_name }}</span>
                </p>
                <p>
                    <label for="phone">Phone</label>
                    <input name="phone" id="phone" type="text" placeholder="Phone" value="{{ contact.phone }}">
                    <span class="error">{{ form.errors.phone }}</span>
                </p>
            </div>
            <button>Save</button>
        </fieldset>
    </form>

    <button id="delete-btn"
            hx-delete="{% url 'contacts:delete' contact.pk %}"
            hx-push-url="true"
            hx-confirm="Are you sure you want to delete this contact?"
            hx-target="body">
        Delete Contact
    </button>

    <p>
        <a href="{% url 'contacts:index' %}">Back</a>
    </p>

{% endblock %}

django/mycontacts/templates/index.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}

    {% include 'archive_ui.html' %}


    <form action="{% url "contacts:index" %}" method="get" class="tool-bar">
        <label for="search">Search Term</label>
        <input id="search" type="search" name="q" value="{{ request.GET.q }}"
               hx-get="{% url "contacts:index" %}"
               hx-trigger="search, keyup delay:200ms changed"
               hx-target="tbody"
               hx-push-url="true"
               hx-indicator="#spinner"/>
        <img style="height: 20px" id="spinner" class="htmx-indicator" src="{% static 'img/spinning-circles.svg' %}"/>
        <input type="submit" value="Search"/>
    </form>

    <form x-data="{ selected: [] }">
        <template
                x-if="selected.length > 0">
            <div class="box info tool-bar flxed top">
                <slot x-text="selected.length"></slot>
                contacts selected

                <button type="button" class="bad bg color border"
                        @click="confirm(`Delete ${selected.length} contacts?`) &&
                    htmx.ajax('DELETE', '{% url 'contacts:delete_all' %}', { source: $root, target: document.body })"
                >Delete
                </button>
                <hr aria-orientation="vertical">
                <button type="button" @click="selected = []">Cancel</button>
            </div>
        </template>
        <table>
            <thead>
            <tr>
                <th></th>
                <th>First</th>
                <th>Last</th>
                <th>Phone</th>
                <th>Email</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% include 'rows.html' %}
            </tbody>
        </table>
        <button hx-delete="{% url 'contacts:delete_all' %}"
                hx-confirm="Are you sure you want to delete these contacts?"
                hx-target="body"
        >
            Delete Selected Contacts
        </button>
    </form>
    <p>
        <a href="{% url 'contacts:new' %}">Add Contact</a>
        <span hx-get="{% url 'contacts:count' %}" hx-trigger="revealed">
          <img id="spinner" style="height: 20px" class="htmx-indicator" src="{% static 'img/spinning-circles.svg' %}"/>
        </span>
    </p>

{% endblock %}

django/mycontacts/templates/layout.html
{% load static %}
<!doctype html>
<html lang="">
<head>
    <title>Contact App</title>
    <link rel="stylesheet" href="https://the.missing.style/v0.2.0/missing.min.css">
    <link rel="stylesheet" href="{% static "site.css" %}">
    <script src="{% static "js/htmx-1.8.0.js" %}"></script>
    <script src="{% static "js/_hyperscript-0.9.7.js" %}"></script>
    <script src="{% static "js/rsjs-menu.js" %}" type="module"></script>
    <script defer src="https://unpkg.com/alpinejs@3/dist/cdn.min.js"></script>
</head>
<body hx-boost="true" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
<main>
    <header>
        <h1>
            <all-caps>contacts.app</all-caps>
            <sub-title>A Demo Contacts Application</sub-title>
        </h1>
    </header>
    {% for message in messages %}
        <div class="flash">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
</main>
</body>
</html>

django/mycontacts/templates/new.html
{% extends 'layout.html' %}

{% block content %}

    <form action="{% url 'contacts:new' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Contact Values</legend>
            <div class="table rows">
                <p>
                    <label for="email">Email</label>
                    <input name="email" id="email" type="text" placeholder="Email"
                           value="{{ request.POST.email|default:'' }}">
                    <span class="error">{{ form.errors.email }}</span>
                </p>
                {{ values }}
                <p>
                    <label for="first_name">First Name</label>
                    <input name="first_name" id="first_name" type="text" placeholder="First Name"
                           value="{{ request.POST.first_name|default:'' }}">
                    <span class="error">{{ form.errors.first }}</span>
                </p>
                <p>
                    <label for="last_name">Last Name</label>
                    <input name="last_name" id="last_name" type="text" placeholder="Last Name"
                           value="{{ request.POST.last_name|default:'' }}">
                    <span class="error">{{ form.errors.last }}</span>
                </p>
                <p>
                    <label for="phone">Phone</label>
                    <input name="phone" id="phone" type="text" placeholder="Phone"
                           value="{{ request.POST.phone|default:'' }}">
                    <span class="error">{{ form.errors.phone }}</span>
                </p>
            </div>
            <button>Save</button>
        </fieldset>
    </form>

    <p>
        <a href="{% url 'contacts:index' %}">Back</a>
    </p>


{% endblock %}

django/mycontacts/templates/rows.html
{% for contact in contacts %}
    <tr>
        <td><input type="checkbox" name="selected_contact_ids" value="{{ contact.id }}"
                   x-model="selected"></td>
        <td>{{ contact.first_name }}</td>
        <td>{{ contact.last_name }}</td>
        <td>{{ contact.phone }}</td>
        <td>{{ contact.email }}</td>
        <td>
            <div data-overflow-menu>
                <button type="button" aria-haspopup="menu"
                        aria-controls="contact-menu-{{ contact.id }}"
                >Options
                </button>
                <div role="menu" hidden id="contact-menu-{{ contact.id }}">
                    <a role="menuitem" href="{% url 'contacts:edit' contact.id %}">Edit</a>
                    <a role="menuitem" href="{% url 'contacts:details' contact.id %}">View</a>
                    <a role="menuitem" href="#"
                       hx-delete="{% url 'contacts:delete' contact.id %}"
                       hx-confirm="Are you sure you want to delete this contact?"
                       hx-swap="outerHTML swap:1s"
                       hx-target="closest tr">Delete</a>
                </div>
            </div>
        </td>
    </tr>
{% endfor %}